### ISSUE TITLE
lesson1 (by @forno)

### ISSUE THREAD

**Issue by forno** [H28-CIRKIT-ARC-1stGrade/Git_lesson#1]
こんにちは @forno です。

Gitの練習がしたいようなので、課題とか求めているのでは無いだろうか(偏見)。ということで、適当に考えてみました。

## 第一の課題
masterブランチから新しくブランチを切って自分のアカウント名のファイルを作り、そのブランチをプッシュ。その後、GithubでPull-requestを開き、他人のレビュを貰う。

如何でしょうか。
初めての課題ですが、多少はGitの取り扱い方も知っているでしょうし、複合的課題としてみました。

出したPull-requestはマージしてもいいですし、しなくてもいいです。ただ、他人にレビュはしてもらいましょう。
レビュのやり方は知らなければ聞いてくださいまし。

しばらくはマージせずに、複数人のブランチが同じmasterから生えているのをGithubのGraphsのnetworkとかから眺めるのも割と楽しいです。
一通り楽しんだらマージして、複数人の作業がmasterに帰っていくGraphsのnetworkを眺めるのも楽しいです。

では、そんなこともしてみてくださいまし。

**Comment by forno** [comment]
ちなみに「ブランチを切る」という表現は、あるブランチから新しいブランチを作成し、そちらにチェックアウトすることを意味します。
よく「masterブランチを切る」などと表現され、これはmasterブランチから新しいブランチを作成し、そちらへチェックアウトすることを意味しています。

新しいブランチ名は適当に好きなものを使えば良いです。
現在のCIR-KITでは名前のイニシャルを用いて `dy/add/tutorial-file` といったように、 「Doi Yusuke」が「ファイルの追加」する。「チュートリアルファイル」を。みたいな感じになってます。

では、一先ず参加している一回生だけでもやってみてくださいまし。

**Comment by tanacchi** [comment]
めっちゃありがたいです！ありがとうございます  
近々やってみます

**Comment by forno** [comment]
challenge Label 作りました。 活用してくださいまし。

**Comment by forno** [comment]
#6 で回答例出しました。
みんなもやってみてね。

**Comment by tanacchi** [comment]
ありがとうございます！
（明日からテスト勉強するので）
中間終わったら頑張ってみます。。。

**Comment by forno** [comment]
中間頑張れー

**Comment by tanacchi** [comment]
あざっす！！！
