### ISSUE TITLE
Memberの権限について

### ISSUE THREAD

**Issue by forno** [H28-CIRKIT-ARC-1stGrade/Git_lesson#3]
恐らくデフォルトの設定だと、Organizationに誘ったMember権限の人はリポジトリへのWrite権限が無いです。

解決方法は大きく分けて３つ
1. メンバーを全員Owner権限に変更する
2. 設定画面にいってMemberの権限にWriteを加える
3. 個別のリポジトリに Collaborator 登録する

リポジトリに変更を加えられなければ「せっかく入ったのに…」みたいになりますので、設定見なおしてみてください。

ちなみになんで設定が正しくないと思ったかというと、Write権限があるとリポジトリが自動的にWatchに追加されるからです。

ではでは。

**Comment by forno** [comment]
あ、一応私をOwner権限で突っ込んでおいて貰えると助かりますー。
設定漏れとか無いかチェックしてあげたいですし。

**Comment by tanacchi** [comment]
全員にOwner権限をもたせるかたちで解決しました  
ありがとうございました  
Invite送りますね〜

**Comment by forno** [comment]
全員Owner権限になっているのを確認しましたー
