### ISSUE TITLE
間違ってmasterに直接プッシュしないようにプロテクトかけた(過去形)

### ISSUE THREAD

**Issue by forno** [H28-CIRKIT-ARC-1stGrade/Git_lesson#4]
ブランチを切って作業することはGit systemのうえでは結構大切なことなので、ブランチを切らない悪い子は「メッ」します。
masterブランチへPull-requestを出さずにmergeすることができないようプロテクトをかけました。

さて、それでも初めの頃は誤ってmasterにcommitしてしまうこともあるでしょう。
焦る必要性はありません。その時は、とりあえずブランチをそのまま切ってください。以下手順です。

手順 | 説明
--- | ---
`git commit` | 誤ってmasterのままコミット
`git status` | やべ、masterだったわと気づく
`git branch dy/add/tutorial-file` | とりあえずブランチを作る
`git branch` | ブランチの確認。dy/add/tutorial-fileが本当にできたか確認する。
`git reset --hard origin/master` | 今居るのはmasterなのでresetを使ってリモートのmasterで上書きする
`git checkout dy/add/tutorial-file` | 作ったブランチに移動して作業を続ける

こんな感じの操作になります。 確認が冗長な説明ですが、確認は大切です。 これでも私は不安なのでブランチの確認のところは実際にチェックアウトしてファイルが抜けてないか確かめる程ですが、流石に長くなりすぎるので省略しました。

それでは良いGitライフを。

**Comment by tanacchi** [comment]
ありがとうございます！  
（上の操作で何をしているのかはわかりますが
ブランチだのマージだのはまだぼんやりとした理解なので）  
勉強します〜

**Comment by forno** [comment]
議論用のIssueでないので閉じます。
